services:
  nginx:
    image: nginx:stable-alpine
    container_name: domain_check_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - domain_check_network

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.Dockerfile
    container_name: domain_check_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - domain_check_network

  mysql:
    image: mysql:8.0
    container_name: domain_check_db
    restart: unless-stopped
    ports:
      - "3400:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - domain_check_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - domain_check_network

networks:
  domain_check_network:

volumes:
  domain_check_db_data:
